"""Criando tabelas

Revision ID: 5537b9707528
Revises: c0c3c48b9cae
Create Date: 2026-07-16 09:46:02.788561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5537b9707528'
down_revision = 'c0c3c48b9cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parkings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('ocupada', sa.Boolean(), nullable=True),
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spots')
    op.drop_table('parkings')
    # ### end Alembic commands ###
